In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
import ast

In [ ]:
from google.colab import drive
import ast
# Mount Google Drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
num_channels = 6

# Initialize an empty list to store data for each channel
channel_data = []

# Define the full file paths for your data files
y_train_files = [
    '/content/drive/My Drive/tribo/y_train_1.txt',
    '/content/drive/My Drive/tribo/y_train_2.txt',
    '/content/drive/My Drive/tribo/y_train_3.txt',
    '/content/drive/My Drive/tribo/y_train_4.txt',
    '/content/drive/My Drive/tribo/y_train_5.txt',
    '/content/drive/My Drive/tribo/y_train_6.txt'
]

# Load data from each text file and append it to channel_data
for filename in y_train_files:
    with open(filename, 'r') as file:
        lines = file.readlines()
        channel_values = [list(map(float, line.strip().split())) for line in lines]
        channel_data.append(channel_values)

# Convert channel_data to a NumPy array with shape (data_size, sequence_length, num_channels)
#X = np.array(channel_data)
#X= np.array(channel_data)
X = np.array(channel_data).transpose(1, 2, 0)


y_train = '/content/drive/My Drive/tribo/label_data.txt'
with open(y_train, 'r') as file:
    lines = file.readlines()
    y_train = [int(value) for line in lines for value in line.strip().split()]

y= np.array(y_train)
#print(X)
#print(X)
print(np.shape(y))
print(y)

(126,)
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

# Generate synthetic data for two classes
data_size = 126
sequence_length = 200
num_channels = 6  # Number of input channels
num_classes = 2

# Create synthetic data with random values between 0 and 1 for 6 channels
#X = np.random.rand(data_size, sequence_length, num_channels)
#print(X)
#print(np.shape(X))
# Generate random labels for binary classification (0 or 1)
#y = np.random.randint(0, num_classes, size=data_size)
print(y)
print(np.shape(y))
# One-hot encode the target labels
#y = to_categorical(y, num_classes)
y = to_categorical(y - 1, num_classes)  # Subtract 1 to make class labels 0 and 1

#print(y)
#print(np.shape(y))
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
#X_train,y_train = train_test_split(X, y)
#X_train=X
#y_train=Y
#X_train, X_test, y_train, y_test = train_test_split(X, Y,X_test ,y_test )
# Create a Sequential model
model = Sequential()

# Adjust the input shape to accept 6 channels
model.add(Conv1D(32, kernel_size=3, activation='relu', input_shape=(sequence_length, num_channels)))

# Add a Max Pooling Layer with pool size 2
model.add(MaxPooling1D(pool_size=2))

# Add another Conv1D layer with 64 filters and 'relu' activation
model.add(Conv1D(64, kernel_size=3, activation='relu'))

# Add another Max Pooling Layer with pool size 2
model.add(MaxPooling1D(pool_size=2))

# Flatten the output from the previous layer
model.add(Flatten())

# Add a fully connected layer with 128 neurons and 'relu' activation
model.add(Dense(128, activation='relu'))

# Add a Dropout layer to prevent overfitting
model.add(Dropout(0.5))

# Add the output layer with 2 units (binary classification) and 'softmax' activation
model.add(Dense(2, activation='softmax'))

# Compile the model with binary cross-entropy loss, optimizer, and accuracy metric
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model on the training data
model.fit(X_train, y_train, epochs=1000, batch_size=32, validation_data=(X_test, y_test))

# Evaluate the model on the test data
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}')

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
(126,)
Epoch 1/1000
4/4 [==============================] - 1s 89ms/step - loss: 11.5222 - accuracy: 0.5800 - val_loss: 4.2684 - val_accuracy: 0.6538
Epoch 2/1000
4/4 [==============================] - 0s 29ms/step - loss: 7.4228 - accuracy: 0.5700 - val_loss: 3.5906 - val_accuracy: 0.5769
Epoch 3/1000
4/4 [==============================] - 0s 25ms/step - loss: 4.9787 - accuracy: 0.5600 - val_loss: 3.6049 - val_accuracy: 0.4615
Epoch 4/1000
4/4 [==============================] - 0s 26ms/step - loss: 5.2395 - accuracy: 0.6100 - val_loss: 2.7158 - val_accuracy: 0.5385
Epoch 5/1000
4/4 [==============================] - 0s 34ms/step - loss: 3.0516 - accuracy: 0.6400 - val_loss: 0.9909 - val_accuracy: 0.7308
Epoch 6/1000
4/4 [============

In [ ]:
from tensorflow.keras.models import load_model

# ... (train and build your model)

# Save the trained model to a file (e.g., model.h5)
model.save('/content/drive/My Drive/tribo/your_model.h5')

In [ ]:
loaded_model = load_model('/content/drive/My Drive/tribo/your_model.h5')


In [ ]:
# Evaluate the model on the test data
loss, accuracy = model.evaluate(X_test, y_test)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Convert the one-hot encoded predicted labels back to binary labels (0 or 1)
y_pred_binary = np.argmax(y_pred, axis=1)

# Convert one-hot encoded true labels back to binary labels (0 or 1)
y_true_binary = np.argmax(y_test, axis=1)

# Print true labels and predicted labels side by side
for true_label, pred_label in zip(y_true_binary, y_pred_binary):
    print(f"True Label: {true_label}, Predicted Label: {pred_label}")

print(f'Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}')


1/1 [==============================] - 0s 140ms/step
True Label: 1, Predicted Label: 1
True Label: 0, Predicted Label: 0
True Label: 1, Predicted Label: 0
True Label: 1, Predicted Label: 0
True Label: 1, Predicted Label: 1
True Label: 1, Predicted Label: 1
True Label: 0, Predicted Label: 0
True Label: 0, Predicted Label: 0
True Label: 1, Predicted Label: 1
True Label: 0, Predicted Label: 0
True Label: 0, Predicted Label: 0
True Label: 1, Predicted Label: 1
True Label: 0, Predicted Label: 0
True Label: 1, Predicted Label: 1
True Label: 1, Predicted Label: 1
True Label: 0, Predicted Label: 0
True Label: 1, Predicted Label: 1
True Label: 0, Predicted Label: 0
True Label: 0, Predicted Label: 0
True Label: 0, Predicted Label: 0
True Label: 0, Predicted Label: 0
True Label: 0, Predicted Label: 0
True Label: 1, Predicted Label: 1
True Label: 0, Predicted Label: 0
True Label: 0, Predicted Label: 0
True Label: 0, Predicted Label: 0
Test Loss: 1.0032, Test Accuracy: 0.9231


In [ ]:
num_channels = 6

# Initialize an empty list to store data for each channel
channel_data = []

# Define the full file paths for your data files
y_check_files = [
    '/content/drive/My Drive/tribo/check/y_check_1.txt',
    '/content/drive/My Drive/tribo/check/y_check_2.txt',
    '/content/drive/My Drive/tribo/check/y_check_3.txt',
    '/content/drive/My Drive/tribo/check/y_check_4.txt',
    '/content/drive/My Drive/tribo/check/y_check_5.txt',
    '/content/drive/My Drive/tribo/check/y_check_6.txt'
]

# Load data from each text file and append it to channel_data
for filename in y_check_files:
    with open(filename, 'r') as file:
        lines = file.readlines()
        channel_values = [list(map(float, line.strip().split())) for line in lines]
        channel_data.append(channel_values)

# Convert channel_data to a NumPy array with shape (data_size, sequence_length, num_channels)
#X = np.array(channel_data)
#X= np.array(channel_data)
input_sample = np.array(channel_data).transpose(1, 2, 0)
print(input_sample)

[[[ 1.  0.  4.  0.  0.  2.]
  [19.  0.  0. 35.  0.  2.]
  [11.  6.  0. 51.  0.  2.]
  ...
  [ 1.  0.  6.  0. 24.  0.]
  [ 0.  5. 11.  0.  0.  1.]
  [ 0.  3.  0.  0. 34.  2.]]]


In [ ]:
# Assuming you have already trained your model and have it saved as 'model'

# Create a single input sample (modify this according to your data)
#input_sample = np.random.rand(sequence_length, num_channels)  # Replace with your own input
print(input_sample)
# Reshape the input sample to match the expected shape by the model
input_sample = input_sample.reshape(1, sequence_length, num_channels)

# Make a prediction for the input sample
predicted_label = model.predict(input_sample)

# Convert the one-hot encoded predicted label back to binary label (0 or 1)
predicted_label_binary = np.argmax(predicted_label, axis=1)

print(f"Predicted Label: {predicted_label_binary[0]}")







[[[ 1.  0.  4.  0.  0.  2.]
  [19.  0.  0. 35.  0.  2.]
  [11.  6.  0. 51.  0.  2.]
  ...
  [ 1.  0.  6.  0. 24.  0.]
  [ 0.  5. 11.  0.  0.  1.]
  [ 0.  3.  0.  0. 34.  2.]]]
1/1 [==============================] - 0s 26ms/step
Predicted Label: 1
